[tool.poetry]
name = "stigg-api-client"
version = "0.439.0"
description = ""
authors = ["Stigg <support@stigg.io>"]
readme = "README.md"
packages = [{ include = "stigg" }]

[tool.poetry.dependencies]
python = "^3.7"
sgqlc = "^16.0"
graphql-core = "3.1.6"
flake8 = "^5.0.4"
black = "^22.8.0"
requests = "^2.28.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
