variables:
  SOURCE_DIR: bloic

stages:
  - test
  - build
  - deploy
  - release

flake8:
  stage: test
  image:
    name: alpine/flake8
    entrypoint: [""]
  script:
    - flake8 --ignore=E501 ${SOURCE_DIR}

isort:
  stage: test
  image: xcgd/isort
  script:
    - isort -c ${SOURCE_DIR}

build:
  stage: build
  image: python:3.11-alpine
  before_script:
    - apk update && apk add git
    - pip install --upgrade build
  script:
    - python -m build
  artifacts:
    paths:
      - dist/*
    expire_in: 1h

deploy:
  stage: deploy
  image: python:3.11-alpine
  needs:
    - job: build
      artifacts: true
  before_script:
    - pip install --upgrade twine
  script:
    - twine upload --non-interactive --username ${PYPI_USERNAME} --password ${PYPI_PASSWORD} dist/*
  rules:
    - if: $CI_COMMIT_TAG != null

release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    - if: $CI_COMMIT_TAG != null
  variables:
    PYPI_PROJECT_NAME: bloic   
  script:
    - echo "Running the release job."
  release:
    tag_name: $CI_COMMIT_TAG
    name: '$CI_COMMIT_TAG'
    description: '$CI_COMMIT_TAG_MESSAGE'
    assets:
      links:
        - name: ${PYPI_PROJECT_NAME} ${CI_COMMIT_TAG}
          url: https://pypi.org/project/${PYPI_PROJECT_NAME}/${CI_COMMIT_TAG}/
          link_type: 'package'
