[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "capabilities"
dynamic = ["version"]
# version="0.3.6"
authors = [
  { name="Blazon AI", email="support@blazon.ai" },
]
description = "Build trusted, faster, and more powerful applications with the Blazon Capabilities API."
readme = "README.md"
license = { file="LICENSE" }
requires-python = ">=3.8"
dependencies = [
  "fire",
  "requests",
  "dacite",
  "asyncio",
  "aiohttp",
  "pdfminer.six",
  "tiktoken",
  "blobfile",
  "pydantic",
  "pydantic[dotenv]",
  "rich",
  "typer",
  "openai",
  "backoff",
  "diskcache",
  "google",
  "openai",
  "textual",
  "numpy",
]

[project.scripts]
capabilities = "capabilities.cli:app"

[tool.hatch.version]
path = "capabilities/__about__.py"

[project.optional-dependencies]
search = [
  "pyllamacpp",
  "python-magic",
  "bs4",
]
nomic = [
  "nomic",
]
sentence-transformers = [
  "sentence-transformers"
]
agent = [
    "google"
]

[tool.hatch.envs.default]
dependencies = [
  "coverage[toml]>=6.5",
  "pytest",
  "pytest-snapshot",
  "hypothesis",
  "numpy",
  "torch",
  "nomic",
  "sentence-transformers",
  "requests",
  "dacite",
  "aiohttp",
  "tiktoken",
  "pyllamacpp",
  "python-magic",
  "bs4",
  "google",
  "typing_extensions",
]
[tool.hatch.envs.default.scripts]
test = "pytest {args:tests}"
test-cov = "coverage run -m pytest {args:tests}"
cov-report = [
  "- coverage combine",
  "coverage report",
]
cov = [
  "test-cov",
  "cov-report",
]
[[tool.hatch.envs.all.matrix]]
python = ["3.8", "3.9", "3.10", "3.11"]
