[tool.poetry]
name = "crispr_shrinkage"
version = "0.1.69"
description = ""
authors = ["Basheer Becerra <bbecerra@fas.harvard.edu>"]
readme = "README.md"
packages = [{include = "crispr_shrinkage"}]

[tool.poetry.dependencies]
python = ">=3.8,<3.12"
numpy = "^1.24.1"
scipy = "^1.10.0"
matplotlib = "^3.6.3"


[tool.poetry.group.dev.dependencies]
jupyter = "^1.0.0"
sklearn = "^0.0.post1"
docker="6.0.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

