[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "pycelium-specifications"
version = "0.0.2.2"
authors = [
  { name="k98kurz", email="k98kurz@gmail.com" },
]
description = "Library of common interfaces for the Pycelium project."
readme = "readme.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: ISC License (ISCL)",
    "Operating System :: OS Independent",
    "Topic :: Office/Business :: Financial",
    "Topic :: Security :: Cryptography",
    "Topic :: System :: Distributed Computing",
    "Topic :: System :: Networking",
]

[project.urls]
"Homepage" = "https://github.com/k98kurz/pycelium-specifications"
"Bug Tracker" = "https://github.com/k98kurz/pycelium-specifications/issues"