[project]
name = "CrewCo_API"
version = "0.0.1"
authors = [
  { name="CrewCo", email="crewco.99@gmail.com" },
]
description = "CrewCo's beta API"
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/Crew-co/CrewCo_API/"
"Bug Tracker" = "https://github.com/Crew-co/CrewCo_API//issues"


[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"