[tool.poetry]
name = "denemesonuc"
version = "0.2.1"
description = "orbim ölçme değerlendirme şeyi için bir modül"
authors = ["insanolanbiri <erenakgun2007@hotmail.com>"]
license = "GPL-3.0-only"
readme = "README.md"
repository = "https://github.com:/insanolanbiri/denemesonuc"
classifiers = [
    "Operating System :: OS Independent",
]

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/insanolanbiri/denemesonuc/issues"

[tool.poetry.dependencies]
python = "^3.10"
selenium = "^4.8.2"

[tool.poetry.dev-dependencies]
black = "^23.3.0"
isort = "^5.12.0"
pydocstyle = "^6.3.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"
